name: flutterappweb
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  logger: ^2.5.0

  firebase_core: ^3.4.0
  firebase_analytics: ^11.3.0
  firebase_crashlytics: ^4.1.0
  # firebase_crashlytics: 
  #   version: ^4.1.0
  #   flutter:
  #     platforms:
  #       android:
        # ios:

  shared_preferences: ^2.2.1
  json_serializable: ^6.6.1
  json_annotation: ^4.8.1
  dio: ^5.4.2+1

  get_it: ^8.0.3
  retrofit: ^4.0.1
  injectable: ^2.5.0


dev_dependencies:
  injectable_generator: ^2.1.4
  retrofit_generator: ^8.2.1
  build_runner: ^2.3.3
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist.ttf

  uses-material-design: true

  assets:
    - env/
    - assets/i18n/
    - assets/images/
