// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2wbGz7oXgyD7ft46u2EoRgXMa6QeaRz4',
    appId: '1:1051617161658:web:b2431a84c87d17f2e3ad83',
    messagingSenderId: '1051617161658',
    projectId: 'flutter-template-aad4c',
    authDomain: 'flutter-template-aad4c.firebaseapp.com',
    storageBucket: 'flutter-template-aad4c.firebasestorage.app',
    measurementId: 'G-6EQ9QY8PSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-VIjfAhQUUXGB7uXpxiwTir6_rlGsVsA',
    appId: '1:1051617161658:android:76d95f92b3199ed0e3ad83',
    messagingSenderId: '1051617161658',
    projectId: 'flutter-template-aad4c',
    storageBucket: 'flutter-template-aad4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWTlAVY1KFVtokpEQzZK5BedksJs_tESE',
    appId: '1:1051617161658:ios:657b131513276ea0e3ad83',
    messagingSenderId: '1051617161658',
    projectId: 'flutter-template-aad4c',
    storageBucket: 'flutter-template-aad4c.firebasestorage.app',
    iosBundleId: 'com.jdevsuarez.flutterappweb',
  );
}
